# Boltzmann Machines

For this implementation, I'll use the restricted boltzmann variation just to simplify things and so I don't have to deal with connection between my own inputs and I will have a threshold of 0 so no $\theta$ at all.

So first I need units that are fixed based on the input. I want to store XOR information in my network.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("dark_background")

In [2]:
x = np.array([[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0]])
x

array([[0, 0, 0],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [3]:
(x[:, 0] ^ x[:, 1]) == x[:, 2]

array([ True,  True,  True,  True])

Next I want to design the boltzmann machine so that I have input nodes that connect to densely connected hidden nodes.

A unit in the boltzmann machine connects to other units in a bi directional way and there is a singe weight link connecting them.

In [34]:
weights = np.random.randn(3, 6)

In [35]:
weights

array([[ 2.49671332e-01,  6.69016971e-02, -1.04279911e-01,
        -5.56949080e-01, -5.73765038e-01, -6.13338213e-01],
       [-2.09442784e-01,  6.08921921e-01,  1.12122583e+00,
        -2.50843348e+00, -8.75507343e-01,  1.57198925e+00],
       [-2.05507292e-01,  3.88330715e-04, -6.79320323e-01,
        -1.60437539e+00,  4.65102066e-01, -1.17716699e+00]])

In [40]:
def prob_unit_on(prev_s, incoming_weights, T=1):
	weighted_sum = prev_s@incoming_weights
	return 1/(1 + np.exp(-weighted_sum/T)) # boltzmann dist.

prob_unit_on(x, weights, T=1) # probs of each hidden layer state being 1

array([[0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
        0.5       ],
       [0.39772578, 0.64778345, 0.60871298, 0.01609835, 0.39881495,
        0.59744302],
       [0.51103922, 0.51681616, 0.31354447, 0.10327773, 0.47286096,
        0.1430108 ],
       [0.51005578, 0.66280594, 0.73437728, 0.04455799, 0.19011357,
        0.72285164]])

In [46]:
set_hidden_state = np.array([[1, 0, 0, 0, 0, 1]])
p = prob_unit_on(set_hidden_state, weights.T, T=1) # probs of each visible layer state being 1
p

array([[0.41007221, 0.79617325, 0.20057984]])

In [54]:
def s(probs):
	r = np.random.rand(*probs.shape)
	out = np.zeros_like(probs)
	out[r > probs] = 1
	return out
s(p)

array([[0., 0., 1.]])

In [128]:
forward = s(prob_unit_on(x, weights))
forward

array([[0., 0., 0., 1., 0., 1.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [131]:
backward = s(prob_unit_on(forward, weights.T))
backward

array([[0., 1., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [0., 1., 1.]])